- package.json
- src/rule/type.js
- tests/index.spec.js
support url has query and hash
> fix type url

- README.md
callback should not spread null
> fix(update readme)

- README.md
> docs: small bugs

- src/index.js
> Allow warning function to be overwritten

- README.md
- __tests__/messages.spec.js
- src/util.js
- Added: function support for message.
- Added: Test to cover the new code.
- Updated: Readme with example.
> Added: Support for "function" as message

- README.md
- __tests__/validator.spec.js
- src/util.js
> :bug: Fixed first option not return Promise #168

- src/util.js
> fix process is not defined

- README.md
promise usage set asyncValidator in source is incorrect
> fixed promise usage

- README.md
- package.json
- typings/index.d.ts
option `single ` could not search in project source code, it should be invalidity
> remove readme invalidity option and support typescript

- package.json
Improves dev productivity, working on an other PR right now
> chore: add command `test:watch`

- __tests__/any.spec.js
- src/index.d.ts
- src/validator/any.js
- src/validator/index.js
solves https://github.com/yiminghe/async-validator/issues/74
> feat(any): add any type

- package.json
Modified package.json from “pack build” to “pika-pack build" to support local compilation and pack.
> Modified package.json from “pack build” to “pika-pack build”

- src/index.d.ts
> fix export some types

- .github/workflows/nodejs.yml
- package.json
Add github actions that can replace `travis`.
> add github actions

- __tests__/validator.spec.js
- src/util.js
judge whether objArr is empty to resolve or callback, it fixs no response issure when there is no rules for inputs.
> fix(async-map): judge whether objArr is empty to resolve or callback

- __tests__/object.spec.js
- src/index.js
fix the verification will pass when the value of Object is an empty string
#235
> fix: The verification will pass when the value of Object is an empty string

- src/index.js
Hi,
We want to add customize regexp type like guid type.
> export validators

- __tests__/messages.spec.js
- src/util.js
> fix: do not change custom error texts

- src/index.d.ts
It is to fix the typing of message since it can support function.
> Fix: Add function type for RuleItem.message

- __tests__/array.spec.js
I've created additional tests for this package during a bug finding mission. 
Your package works absolutely fine. Finally, I've found the relevant bug in rc-field-form.
Nonetheless I'd like to give you back my test cases for providing this useful package.
> Add test cases for array type

- README.md
Seems this doc is missing some words.
> doc(readme):  complete sentence.

- __tests__/validator.spec.ts
- src/index.ts
> fix: catch the custom validate function

- src/rule/range.ts
1. fix the words 'length' spell error
> Chore: fix the word 'length' spell error
